
ScreenManager:
    id: screen_manager
    LoginScreen:
        name: "login_screen"
    SignUpScreen:
        name: "signup_screen"
    MainScreen:
        name: "main_screen"



<LoginScreen>:
    FloatLayout:
        orientation: 'vertical'
        
        # Background image
        Image:
            source: root.loginscreen_path
            allow_stretch: True
            keep_ratio: False
            size_hint: 1, 0.45
            y: self.parent.height * 0.55

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.6
            padding: ["50dp", "100dp", "50dp", "100dp"]
            spacing: "10dp"

            canvas.before:
                Color:
                    rgba: (0.7, 0.87, 1, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [30, 30, 0, 0]

            Label:
                text: "MediEvaluate"
                font_size: '30sp'
                bold: True
                color: (0, 0, 0, 1)
                size_hint_y: None
                height: "50dp"

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: "120dp"
                spacing: "5dp"
                pos_hint: {"center_x": 0.5}

                TextInput:
                    id: email_input
                    hint_text: "Email"
                    size_hint: 0.9, None
                    height: "40dp"
                    pos_hint: {"center_x": 0.5}
                    background_color: (1, 1, 1, 0.3)
                    foreground_color: (0, 0, 0, 1)

                TextInput:
                    id: password_input
                    hint_text: "Password"
                    password: True
                    size_hint: 0.9, None
                    height: "40dp"
                    pos_hint: {"center_x": 0.5}
                    background_color: (1, 1, 1, 0.3)
                    foreground_color: (0, 0, 0, 1)

            # Sign Up and Forgot Password buttons
            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: None
                height: "40dp"
                spacing: "10dp"
                pos_hint: {"center_x": 0.5}

                Button:
                    text: "Sign Up"
                    background_color: (0, 0, 0, 0)
                    color: (0, 0, 1, 1)
                    on_press: root.go_to_signup()

            # Sign In Button
            Button:
                text: "Sign In"
                size_hint: 0.6, None
                height: "45dp"
                pos_hint: {"center_x": 0.5}
                background_color: (0.1, 0.4, 0.6, 1)  # Darker blue
                on_press: root.login()

<MainScreen>:
    BoxLayout:
        orientation: 'vertical'

        ScreenManager:
            id: main_screen_manager
            SearchMedicineScreen:
                name: 'medicine_screen'
            SearchArticlesScreen:
                name: 'article_screen'
            WeGamingScreen:
                name: 'gaming_screen'
            MapScreen:
                name: 'map_screen'
            ProfileScreen:
                name: 'profile_screen'

        BoxLayout:
            size_hint_y: None
            height: '75dp'
            spacing: 5

            canvas.before:
                Color:
                    rgba: (1.0, 0.976, 0.913, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [10]
            Button:
                background_normal: root.home_logo_path
                size_hint: None, None
                width: self.height
                height: min(root.width / 5, 75)  
                on_release: main_screen_manager.current = 'medicine_screen'
            Button:
                background_normal: root.article_logo_path
                size_hint: None, None
                width: self.height
                height: min(root.width / 5, 75) 
                on_release: main_screen_manager.current = 'article_screen'
            Button:
                background_normal: root.game_logo_path
                size_hint: None, None
                width: self.height
                height: min(root.width / 5, 75) 
                on_release: main_screen_manager.current = 'gaming_screen'
            Button:
                background_normal: root.map_logo_path
                size_hint: None, None
                width: self.height
                height: min(root.width / 5, 75) 
                on_release: main_screen_manager.current = 'map_screen'
            Button:
                background_normal: root.man_logo_path
                size_hint: None, None
                width: self.height
                height: min(root.width / 5, 75) 
                on_release: main_screen_manager.current = 'profile_screen'

<SignUpScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(10)
        canvas.before:
            Color:
                rgba: (0.678, 0.85, 0.921, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        Button:
            text: "Back to Login"
            size_hint_y: None
            height: dp(50)
            background_color: (0.1, 0.4, 0.6, 1)
            on_release: app.root.current = 'login_screen'
        Label:
            text: "Sign Up"
            font_size: "24sp"
            bold: True
            size_hint_y: None
            height: dp(40)
        Label:
            text: "Email:"
            size_hint_y: None
            height: dp(20)
        TextInput:
            id: email_input
            hint_text: "Enter email"
            multiline: False
        Label:
            text: "Password:"
            size_hint_y: None
            height: dp(20)
        TextInput:
            id: password_input
            hint_text: "Enter password"
            password: True
            multiline: False
        Button:
            text: "Sign Up"
            size_hint_y: None
            height: dp(50)
            background_color: (0.1, 0.4, 0.6, 1)
            on_release: root.sign_up()
        Label:
            id: message_label
            text: ""
            size_hint_y: None
            height: dp(40)


<ProfileScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        canvas.before:
            Color:
                rgba: (0.678, 0.85, 0.921, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: 'Welcome to the Profile Screen!'
            font_size: '18sp'
            size_hint_y: None
            height: '50dp'

        Label:
            id: score_label
            text: "Loading..."  # Default text while fetching data
            font_size: 24
            size_hint_y: None
            color: 0, 0, 0, 1
            height: self.texture_size[1]  # Adjust height based on the text size
        

<SearchMedicineScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10
        canvas.before:
            Color:
                rgba: (0.678, 0.85, 0.921, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        Spinner:
            id: category_spinner
            text: 'Select Pharmacologic Category'
            values: []
            background_color: (0.247, 0.517, 0.631, 1)
            on_text: root.on_category_select(self, self.text)
        
        Spinner:
            id: generic_spinner
            text: 'Select Generic Name'
            values: []
            background_color: (0.247, 0.517, 0.631, 1)
            on_text: root.on_generic_select(self, self.text)
            disabled: True
        
        Spinner:
            id: strength_spinner
            text: 'Select Dosage Strength and Form'
            values: []
            background_color: (0.247, 0.517, 0.631, 1)
            on_text: root.on_strength_select(self, self.text)
            disabled: True
        
        Spinner:
            id: form_spinner
            text: 'Select Dosage Form'
            values: []
            background_color: (0.247, 0.517, 0.631, 1)
            on_text: root.on_form_select(self, self.text)
            disabled: True
        
        Spinner:
            id: brand_spinner
            text: 'Select Brand Name'
            values: []
            background_color: (0.247, 0.517, 0.631, 1)
            disabled: True

<SearchArticlesScreen>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: (0.678, 0.85, 0.921, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: "Medical News"
            size_hint_y: None
            height: "50dp"
            font_size: "24sp"
            bold: True

        ScrollView:
            size_hint: 1, 1
            do_scroll_x: False

            GridLayout:
                id: article_list
                cols: 1
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10

<WeGamingScreen>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: (0.678, 0.85, 0.921, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            id: score_label
            text: "Score: " + str(root.score)
            size_hint_y: None
            color: 0, 0, 0, 1
            height: '30dp'
        AsyncImage:
            id: img
            source: root.image_source
            size_hint_y: 0.6
        GridLayout:
            cols: 1
            spacing: 10
            size_hint_y: 0.4
            Button:
                id: choice_1
                background_color: (0,0,0,0)
                on_press: root.check_answer(self)
                canvas.before:
                    Color: 
                        rgba: 0.247, 0.517, 0.631, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20]
            Button:
                id: choice_2
                background_color: (0,0,0,0)
                on_press: root.check_answer(self)
                canvas.before:
                    Color:
                        rgba: 0.247, 0.517, 0.631, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20]
        

<MapScreen>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: (0.678, 0.85, 0.921, 1)
            Rectangle:
                pos: self.pos
                size: self.size
        MapView:
            id: map_view
            lat: 14.8527
            lon: 120.8160
            zoom: 15
        
