#:import MapView kivy.garden.mapview.MapView

<LoginScreen>:
    FloatLayout:
        orientation: 'vertical'
        
        # Background image
        Image:
            source: 'loginscreen.png'
            allow_stretch: True
            keep_ratio: False
            size_hint: 1, 0.45
            y: self.parent.height * 0.55

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.6
            padding: ["50dp", "100dp", "50dp", "100dp"]
            spacing: "10dp"

            canvas.before:
                Color:
                    rgba: (0.7, 0.87, 1, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [30, 30, 0, 0]

            Label:
                text: "MediEvaluate"
                font_size: '24sp'
                bold: True
                color: (0, 0, 0, 1)
                size_hint_y: None
                height: "50dp"

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: "120dp"
                spacing: "5dp"
                pos_hint: {"center_x": 0.5}

                TextInput:
                    id: email_input
                    hint_text: "Email"
                    size_hint: 0.9, None
                    height: "40dp"
                    pos_hint: {"center_x": 0.5}
                    background_color: (1, 1, 1, 0.3)
                    foreground_color: (0, 0, 0, 1)

                TextInput:
                    id: password_input
                    hint_text: "Password"
                    password: True
                    size_hint: 0.9, None
                    height: "40dp"
                    pos_hint: {"center_x": 0.5}
                    background_color: (1, 1, 1, 0.3)
                    foreground_color: (0, 0, 0, 1)

            # "Sign Up" and "Forgot Password?" in a Row
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: "50dp"  # Adjusted to fit both labels without too much space
                spacing: "5dp"  # Reduced spacing for a compact look
                pos_hint: {"center_x": 0.5}

                Label:
                    text: "Sign Up"
                    color: (0, 0, 0, 1)
                    font_size: '16sp'
                    size_hint_y: None
                    height: "20dp"  # Adjusted height

                Label:
                    text: "Forgot Password?"
                    color: (0, 0, 0, 1)
                    font_size: '16sp'
                    size_hint_y: None
                    height: "20dp"  # Adjusted height

            # Sign In Button
            Button:
                text: "Sign In"
                size_hint: 0.6, None
                height: "45dp"
                pos_hint: {"center_x": 0.5}
                background_color: (0.1, 0.4, 0.6, 1)  # Darker blue




<SearchMedicineScreen>:
    BoxLayout:
        padding: 10
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '50dp'
            spacing: 5
            TextInput:
                hint_text: 'Search for the type of medicine you need.'
                multiline: False
                size_hint_y: None
                height: '50dp'
            Button:
                text: 'Search'
                height: '50dp'
                width: '50dp'
                size_hint_x: None
                size_hint_y: None
        BoxLayout:
            ColoredBox:
                color: (1, 1, 1, 0.25)
                size_hint_x: 0.5
            ColoredBox:
                color: (1, 1, 1, 0.5)
                size_hint_x: 0.5

<ColoredBox@Widget>
    color: (1, 1, 1, 1)
    canvas.before:
        Color: 
            rgba: root.color
        Rectangle:
            pos: self.pos
            size: self.size


<SearchArticlesScreen>:
    BoxLayout:
        padding: 10
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '50dp'
            spacing: 5
            TextInput:
                hint_text: 'Search for articles.'
                multiline: False
                size_hint_y: None
                height: '50dp'
            Button:
                text: 'Search'
                height: '50dp'
                width: '50dp'
                size_hint_x: None
                size_hint_y: None


        BoxLayout:
            ColoredBox:
                color: (1, 1, 1, 0.75)

<WeGamingScreen>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'vertical'
            padding: 10

            Label:
                id: score_label
                text: "Score: " + str(root.score)
                size_hint_y: None
                height: '30dp'

            Image:
                id: img
                source: root.image_source
                size_hint_y: 0.6

            GridLayout:
                cols: 1
                spacing: 10
                size_hint_y: 0.4

                Button:
                    id: choice_1
                    on_press: root.check_answer(self)
                Button:
                    id: choice_2
                    on_press: root.check_answer(self)

        BoxLayout:
            size_hint_y: None
            height: '100dp'
            Button:
                text: 'Home'
                on_press: app.root.current = 'home_screen'
            Button:
                text: 'Search Medicine'
                on_press: app.root.current = 'medicine_screen'
            Button:
                text: 'Research Articles'
                on_press: app.root.current = 'article_screen'
            Button:
                text: 'Game'
                on_press: app.root.current = 'gaming_screen'
            Button:
                text: 'Nearest Drug Stores'
                on_press: app.root.current = 'map_screen'

ScreenManager:
    id: screen_manager
    LoginScreen:
        name: "login_screen"
    HomeScreen:
        name: 'home_screen'
    SearchMedicineScreen:
        name: 'medicine_screen'
    SearchArticlesScreen:
        name: 'article_screen'
    WeGamingScreen:
        name: 'gaming_screen'
    MapScreen:
        name: 'map_screen'


<HomeScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10

        Label:
            text: 'This is the home screen. You must log in first.'
            font_size: '18sp'
            size_hint_y: None
            height: '50dp'

        BoxLayout:
            size_hint_y: None
            height: '100dp'
            Button:
                text: 'Home'
                on_press: app.root.current = 'home_screen'
            Button:
                text: 'Search Medicine'
                on_press: app.root.current = 'medicine_screen'
            Button:
                text: 'Research Articles'
                on_press: app.root.current = 'article_screen'
            Button:
                text: 'Game'
                on_press: app.root.current = 'gaming_screen'
            Button:
                text: 'Nearest Drug Stores'
                on_press: app.root.current = 'map_screen'
            

<MapScreen>:
    BoxLayout:
        orientation: 'vertical'
        MapView:
            id: map_view
            lat: 14.8527
            lon: 120.8160
            zoom: 20

        BoxLayout:
            size_hint_y: None
            height: '100dp'
            Button:
                text: 'Home'
                on_press: app.root.current = 'home_screen'
            Button:
                text: 'Search Medicine'
                on_press: app.root.current = 'medicine_screen'
            Button:
                text: 'Research Articles'
                on_press: app.root.current = 'article_screen'
            Button:
                text: 'Game'
                on_press: app.root.current = 'gaming_screen'
            Button:
                text: 'Nearest Drug Stores'
                on_press: app.root.current = 'map_screen'



    


